name: Validate Module
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  validate:
    name: Validate Terraform Module
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        tf_version:
        - terraform:1.7
        - terraform:latest
        - opentofu:latest
    container:
      image: ${{ startsWith(matrix.tf_version, 'terraform') && format('{0}/{1}', 'docker.io/hashicorp', matrix.tf_version) || format('{0}/{1}', ' ghcr.io/opentofu', matrix.tf_version) }}
    env:
      TF_EXE: ${{ startsWith(matrix.tf_version, 'terraform') && 'terraform' || 'tofu' }}
    steps:
    - name: git checkout
      uses: actions/checkout@v4
    - name: Initialize ${{ matrix.tf_version }}
      run: |
        "${TF_EXE}" init -backend=false
    - name: Validate Terraform Module Syntax
      run: |
        "${TF_EXE}" validate
  #security_scanner:
  #  name: Run tfsec Security Scanner
  #  runs-on: ubuntu-20.04
  #  container:
  #    image: docker.io/liamg/tfsec:v0.25.0
  #  steps:
  #  - name: git checkout
  #    uses: actions/checkout@v2
  #  - name: Run security scanner
  #    run: tfsec .
